version: '3.8'
services:
  cache:
    container_name: picasso-cache
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache-vol:/data
  dj:
#    container_name: picasso-dj
    image: phdmabuze/picasso-dj
    build: ./dj
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./media-vol/
        target: /upload
      - type: bind
        source: ./db-vol/
        target: /db-vol
    depends_on:
      - cache
  celery:
#    container_name: picasso-celery
    image: phdmabuze/picasso-dj
    build: ./dj
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./media-vol/
        target: /upload
      - type: bind
        source: ./db-vol/
        target: /db-vol
    command: celery -A dj worker -l INFO
    depends_on:
      - dj
volumes:
  cache:
    driver: local
  dj:
    driver: local